[project]
name = "teoria-computacao"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "notebook>=7.4.4",
    "ruff>=0.12.4",
    "streamlit>=1.47.0",
]

[tool.ruff]
line-length = 210
